import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import NextAuthSessionProvider from "./Providers/NextAuthSessionProvider";
import Theme from "./Provider/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SALFORD",
  description: "Generated by create next app",
  icons: {
    icon: "/logo/logo1.png", // your logo or favicon path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Theme>
          <NextAuthSessionProvider>
            <header>
              <Navbar/>
            </header>
            <section className="px-[1%] md:px-[5%] 2xl:px-[7%] min-h-[calc(100vh-155px)]">
              {children}
            </section>
            <footer>
              <Footer/>
            </footer>
          </NextAuthSessionProvider>
        </Theme>
      </body>
    </html>
  );
}
